### PR TITLE
add pma-voice to plume esx

### PR DESCRIPTION
**Pull request by AvarianKnight**

### CODE REVIEW

**Comment by TasoOneAsia** [comment]
@tabarra merge this

**Comment by tabarra** [comment]
> @tabarra merge this

tested and working?  
when I tried it didn't work

**Comment by TasoOneAsia** [comment]
Then its an underlying gcphone issue 😢, will test when I get a chance

**Comment by tabarra** [comment]
Added on the latest update. Thanks.

**Pull request closed without merging**
