### PR TITLE
Various bug fixes aswell as updates and QOL changes

### PR DESCRIPTION
**Pull request by Arm-0001**
added multiple scripts such as 

added vstancer: https://hamy.is-stupid.lol/4GunE9RJVR.jpg

and vsync for weather: https://hamy.is-stupid.lol/KSUotQ39oG.mp4
as well as time: https://hamy.is-stupid.lol/KdvSh8JsQY.mp4

as well as updated pma voice and easy admin

### CODE REVIEW

**Comment by tabarra** [comment]
Tested?

**Comment by Hamy-os** [comment]
pending test from @goatg33k

**Comment by Hamy-os** [comment]
@tabarra testing completed all works perfectly

**Comment by tabarra** [comment]
Thanks Hamy.  
Can you please:
1. Increase the version to v3.2.0
2. Move the two new ensures to anotherp lacei n the file? right now it's with the easyadmin stuff, move that up or something

**Comment by Hamy-os** [comment]
yep will do that right now

**Comment by Hamy-os** [comment]
@tabarra done!

**Comment by tabarra** [comment]
Thanks

**Pull request merged**
