### PR TITLE
Update recipe.yaml for PlumeESX to ESXLegacy

### PR DESCRIPTION
**Pull request by DARKDRAGON-LK**
I want use this recipe but there ways some errors and 404s..so i have create a new yaml and tested..I customize your yaml and i think this help some one..
thanks

### CODE REVIEW

**Comment by Hamy-os** [comment]
this recipe is very wrong you are downloading everything twice. anyways I already made one https://github.com/tabarra/PlumeESX-recipe/pull/8

**Comment by DARKDRAGON-LK** [comment]
@Hamy-os i didn't see that earlier bro so i create this one.. thanks you for the comment .btw this recipe work for me perfectly fine for me and i removed old download and use the old directory to run it..

**Comment by Hamy-os** [comment]
> @Hamy-os i didn't see that earlier bro so i create this one.. thanks you for the comment .btw this recipe work for me perfectly fine for me and i removed old download and use the old directory to run it..

still doesn't follow best practises nor is it optimised (least downloads as possible)

**Comment by DARKDRAGON-LK** [comment]
> > @Hamy-os i didn't see that earlier bro so i create this one.. thanks you for the comment .btw this recipe work for me perfectly fine for me and i removed old download and use the old directory to run it..
> 
> still doesn't follow best practises nor is it optimised (least downloads as possible)

sorry for that i'm new to the this kind a stuff

**Comment by Hamy-os** [comment]
> > > @Hamy-os i didn't see that earlier bro so i create this one.. thanks you for the comment .btw this recipe work for me perfectly fine for me and i removed old download and use the old directory to run it..
> > 
> > 
> > still doesn't follow best practises nor is it optimised (least downloads as possible)
> 
> sorry for that i'm new to the this kind a stuff

No problem :D glad you made this! its always nice to see new people making recipes! refer to the documentation if you wish to learn more

**Comment by tabarra** [comment]
fixed in last update.  
thanks for the pr tho

**Pull request closed without merging**
